// // This file was generated by SquareLine Studio
// // SquareLine Studio version: SquareLine Studio 1.3.4
// // LVGL version: 8.3.6
// // Project name: TestDesign

// #include "../ui.h"

// void ui_Screen4_screen_init(void)
// {
//     ui_Screen4 = lv_obj_create(NULL);
//     lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x57626C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_main_stop(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_stop(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_HeaderPanel4 = lv_obj_create(ui_Screen4);
//     lv_obj_set_width(ui_HeaderPanel4, 783);
//     lv_obj_set_height(ui_HeaderPanel4, 37);
//     lv_obj_set_x(ui_HeaderPanel4, 0);
//     lv_obj_set_y(ui_HeaderPanel4, -143);
//     lv_obj_set_align(ui_HeaderPanel4, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_HeaderPanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_HeaderPanel4, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_HeaderPanel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_HeaderPanel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_HeaderPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_DateHeader4 = lv_label_create(ui_Screen4);
//     lv_obj_set_width(ui_DateHeader4, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_DateHeader4, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_DateHeader4, 141);
//     lv_obj_set_y(ui_DateHeader4, -141);
//     lv_obj_set_align(ui_DateHeader4, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_DateHeader4, "Wed, January 31 2023, 3:30 PM");
//     lv_obj_set_style_text_color(ui_DateHeader4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_DateHeader4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_font(ui_DateHeader4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_CardChangename10 = lv_obj_create(ui_Screen4);
//     lv_obj_set_width(ui_CardChangename10, 143);
//     lv_obj_set_height(ui_CardChangename10, 90);
//     lv_obj_set_x(ui_CardChangename10, -133);
//     lv_obj_set_y(ui_CardChangename10, -77);
//     lv_obj_set_align(ui_CardChangename10, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_CardChangename10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_radius(ui_CardChangename10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_CardChangename10, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CardChangename10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CardChangename10, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CardChangename10, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CardChangename10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CardChangename10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_TabViewScr4 = lv_tabview_create(ui_Screen4, LV_DIR_TOP, 60);
//     lv_obj_set_width(ui_TabViewScr4, 255);
//     lv_obj_set_height(ui_TabViewScr4, 37);
//     lv_obj_set_x(ui_TabViewScr4, -114);
//     lv_obj_set_y(ui_TabViewScr4, -143);
//     lv_obj_set_align(ui_TabViewScr4, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_TabViewScr4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_TabViewScr4, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_TabViewScr4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabViewScr4), lv_color_hex(0xB5B5B5),
//                                 LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabViewScr4), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabViewScr4), &lv_font_montserrat_14,
//                                LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabViewScr4), lv_color_hex(0x292929),
//                               LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabViewScr4), 50,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_TabViewScr4), lv_color_hex(0x000000),
//                                   LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_TabViewScr4), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_left(lv_tabview_get_tab_btns(ui_TabViewScr4), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_right(lv_tabview_get_tab_btns(ui_TabViewScr4), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_top(lv_tabview_get_tab_btns(ui_TabViewScr4), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_bottom(lv_tabview_get_tab_btns(ui_TabViewScr4), 25,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_row(lv_tabview_get_tab_btns(ui_TabViewScr4), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_column(lv_tabview_get_tab_btns(ui_TabViewScr4), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabViewScr4), lv_color_hex(0xFFFFFF),
//                                 LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabViewScr4), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_align(lv_tabview_get_tab_btns(ui_TabViewScr4), LV_TEXT_ALIGN_CENTER,
//                                 LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabViewScr4), &lv_font_montserrat_14,
//                                LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabViewScr4), lv_color_hex(0x292929),
//                               LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabViewScr4), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);

//     ui_Monitoring4 = lv_tabview_add_tab(ui_TabViewScr4, "Monitor");

//     ui_Rename4 = lv_tabview_add_tab(ui_TabViewScr4, "Rename");

//     ui_Add_Device4 = lv_tabview_add_tab(ui_TabViewScr4, "Add device");

//     ui_ChangeName10 = lv_textarea_create(ui_Screen4);
//     lv_obj_set_width(ui_ChangeName10, 127);
//     lv_obj_set_height(ui_ChangeName10, 36);
//     lv_obj_set_x(ui_ChangeName10, -133);
//     lv_obj_set_y(ui_ChangeName10, -96);
//     lv_obj_set_align(ui_ChangeName10, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_ChangeName10, "ESP-32 Node10");
//     lv_obj_set_style_text_font(ui_ChangeName10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_SubmitBtn10 = lv_btn_create(ui_Screen4);
//     lv_obj_set_width(ui_SubmitBtn10, 55);
//     lv_obj_set_height(ui_SubmitBtn10, 30);
//     lv_obj_set_x(ui_SubmitBtn10, -168);
//     lv_obj_set_y(ui_SubmitBtn10, -58);
//     lv_obj_set_align(ui_SubmitBtn10, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_SubmitBtn10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_SubmitBtn10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_SubmitBtn10, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_SubmitBtn10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_SubmitBtn10, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_SubmitBtn10, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_SubmitBtn10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_SubmitBtn10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_SubmitBtn10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_SubmitBtn10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sub_btn10;
//     label_sub_btn10 = lv_label_create(ui_SubmitBtn10);
//     lv_label_set_text(label_sub_btn10,"Save");
//     lv_obj_set_style_text_font(label_sub_btn10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sub_btn10);

//     ui_CancleBtn10 = lv_btn_create(ui_Screen4);
//     lv_obj_set_width(ui_CancleBtn10, 55);
//     lv_obj_set_height(ui_CancleBtn10, 30);
//     lv_obj_set_x(ui_CancleBtn10, -98);
//     lv_obj_set_y(ui_CancleBtn10, -58);
//     lv_obj_set_align(ui_CancleBtn10, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_CancleBtn10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_CancleBtn10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_CancleBtn10, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CancleBtn10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CancleBtn10, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CancleBtn10, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CancleBtn10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CancleBtn10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_CancleBtn10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_CancleBtn10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_can_btn10;
//     label_can_btn10 = lv_label_create(ui_CancleBtn10);
//     lv_label_set_text(label_can_btn10,"Cancel");
//     lv_obj_set_style_text_font(label_can_btn10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_can_btn10);

//     ui_changetoRe1btn = lv_btn_create(ui_Screen4);
//     lv_obj_set_width(ui_changetoRe1btn, 22);
//     lv_obj_set_height(ui_changetoRe1btn, 30);
//     lv_obj_set_x(ui_changetoRe1btn, -219);
//     lv_obj_set_y(ui_changetoRe1btn, 16);
//     lv_obj_set_align(ui_changetoRe1btn, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_changetoRe1btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_changetoRe1btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_changetoRe1btn, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_changetoRe1btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_changetoRe1btn, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_changetoRe1btn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_changetoRe1btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_changetoRe1btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_changetoRe1btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_changetoRe1btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sym_btn4;
//     label_sym_btn4 = lv_label_create(ui_changetoRe1btn);
//     lv_label_set_text(label_sym_btn4,"<");
//     lv_obj_set_style_text_font(label_sym_btn4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sym_btn4);

//     lv_obj_add_event_cb(ui_TabViewScr4,ui_event_TabviewScr4,LV_EVENT_ALL,NULL);

// }