// // This file was generated by SquareLine Studio
// // SquareLine Studio version: SquareLine Studio 1.3.4
// // LVGL version: 8.3.6
// // Project name: TestDesign

// #include "../ui.h"

// void ui_Screen3_screen_init(void)
// {
//     ui_Screen3 = lv_obj_create(NULL);
//     lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x57626C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_main_stop(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_stop(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_HeaderPanel2 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_HeaderPanel2, 783);
//     lv_obj_set_height(ui_HeaderPanel2, 37);
//     lv_obj_set_x(ui_HeaderPanel2, 0);
//     lv_obj_set_y(ui_HeaderPanel2, -143);
//     lv_obj_set_align(ui_HeaderPanel2, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_HeaderPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_HeaderPanel2, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_HeaderPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_HeaderPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_HeaderPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_DateHeader2 = lv_label_create(ui_Screen3);
//     lv_obj_set_width(ui_DateHeader2, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_DateHeader2, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_DateHeader2, 141);
//     lv_obj_set_y(ui_DateHeader2, -141);
//     lv_obj_set_align(ui_DateHeader2, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_DateHeader2, "Wed, January 31 2023, 3:30 PM");
//     lv_obj_set_style_text_color(ui_DateHeader2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_DateHeader2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_font(ui_DateHeader2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_CardChangename1 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_CardChangename1, 143);
//     lv_obj_set_height(ui_CardChangename1, 90);
//     lv_obj_set_x(ui_CardChangename1, -163);
//     lv_obj_set_y(ui_CardChangename1, -77);
//     lv_obj_set_align(ui_CardChangename1, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_CardChangename1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_radius(ui_CardChangename1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_CardChangename1, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CardChangename1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CardChangename1, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CardChangename1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CardChangename1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CardChangename1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_TabViewScr3 = lv_tabview_create(ui_Screen3, LV_DIR_TOP, 60);
//     lv_obj_set_width(ui_TabViewScr3, 255);
//     lv_obj_set_height(ui_TabViewScr3, 37);
//     lv_obj_set_x(ui_TabViewScr3, -114);
//     lv_obj_set_y(ui_TabViewScr3, -143);
//     lv_obj_set_align(ui_TabViewScr3, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_TabViewScr3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_TabViewScr3, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_TabViewScr3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabViewScr3), lv_color_hex(0xB5B5B5),
//                                 LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabViewScr3), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabViewScr3), &lv_font_montserrat_14,
//                                LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabViewScr3), lv_color_hex(0x292929),
//                               LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabViewScr3), 50,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_TabViewScr3), lv_color_hex(0x000000),
//                                   LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_TabViewScr3), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_left(lv_tabview_get_tab_btns(ui_TabViewScr3), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_right(lv_tabview_get_tab_btns(ui_TabViewScr3), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_top(lv_tabview_get_tab_btns(ui_TabViewScr3), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_bottom(lv_tabview_get_tab_btns(ui_TabViewScr3), 25,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_row(lv_tabview_get_tab_btns(ui_TabViewScr3), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_column(lv_tabview_get_tab_btns(ui_TabViewScr3), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabViewScr3), lv_color_hex(0xFFFFFF),
//                                 LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabViewScr3), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_align(lv_tabview_get_tab_btns(ui_TabViewScr3), LV_TEXT_ALIGN_CENTER,
//                                 LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabViewScr3), &lv_font_montserrat_14,
//                                LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabViewScr3), lv_color_hex(0x292929),
//                               LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabViewScr3), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);

//     ui_Monitoring2 = lv_tabview_add_tab(ui_TabViewScr3, "Monitor");

//     ui_Rename2 = lv_tabview_add_tab(ui_TabViewScr3, "Rename");

//     ui_Add_Device2 = lv_tabview_add_tab(ui_TabViewScr3, "Add device");

//     ui_ChangeName1 = lv_textarea_create(ui_Screen3);
//     lv_obj_set_width(ui_ChangeName1, 127);
//     lv_obj_set_height(ui_ChangeName1, 36);
//     lv_obj_set_x(ui_ChangeName1, -163);
//     lv_obj_set_y(ui_ChangeName1, -96);
//     lv_obj_set_align(ui_ChangeName1, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_ChangeName1, "ESP-32 Node1");
//     lv_obj_set_style_text_font(ui_ChangeName1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_SubmitBtn1 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_SubmitBtn1, 55);
//     lv_obj_set_height(ui_SubmitBtn1, 30);
//     lv_obj_set_x(ui_SubmitBtn1, -198);
//     lv_obj_set_y(ui_SubmitBtn1, -58);
//     lv_obj_set_align(ui_SubmitBtn1, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_SubmitBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_SubmitBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_SubmitBtn1, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_SubmitBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_SubmitBtn1, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_SubmitBtn1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_SubmitBtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_SubmitBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_SubmitBtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_SubmitBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sub_btn1;
//     label_sub_btn1 = lv_label_create(ui_SubmitBtn1);
//     lv_label_set_text(label_sub_btn1,"Save");
//     lv_obj_set_style_text_font(label_sub_btn1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sub_btn1);


//     ui_CancleBtn1 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_CancleBtn1, 55);
//     lv_obj_set_height(ui_CancleBtn1, 30);
//     lv_obj_set_x(ui_CancleBtn1, -128);
//     lv_obj_set_y(ui_CancleBtn1, -58);
//     lv_obj_set_align(ui_CancleBtn1, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_CancleBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_CancleBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_CancleBtn1, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CancleBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CancleBtn1, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CancleBtn1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CancleBtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CancleBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_CancleBtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_CancleBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_can_btn1;
//     label_can_btn1 = lv_label_create(ui_CancleBtn1);
//     lv_label_set_text(label_can_btn1,"Cancel");
//     lv_obj_set_style_text_font(label_can_btn1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_can_btn1);

//     ui_CardChangename2 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_CardChangename2, 143);
//     lv_obj_set_height(ui_CardChangename2, 90);
//     lv_obj_set_x(ui_CardChangename2, -163);
//     lv_obj_set_y(ui_CardChangename2, 16);
//     lv_obj_set_align(ui_CardChangename2, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_CardChangename2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_radius(ui_CardChangename2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_CardChangename2, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CardChangename2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CardChangename2, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CardChangename2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CardChangename2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CardChangename2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_ChangeName2 = lv_textarea_create(ui_Screen3);
//     lv_obj_set_width(ui_ChangeName2, 127);
//     lv_obj_set_height(ui_ChangeName2, 36);
//     lv_obj_set_x(ui_ChangeName2, -163);
//     lv_obj_set_y(ui_ChangeName2, -3);
//     lv_obj_set_align(ui_ChangeName2, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_ChangeName2, "ESP-32 Node2");
//     lv_obj_set_style_text_font(ui_ChangeName2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_SubmitBtn2 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_SubmitBtn2, 55);
//     lv_obj_set_height(ui_SubmitBtn2, 30);
//     lv_obj_set_x(ui_SubmitBtn2, -198);
//     lv_obj_set_y(ui_SubmitBtn2, 35);
//     lv_obj_set_align(ui_SubmitBtn2, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_SubmitBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_SubmitBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_SubmitBtn2, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_SubmitBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_SubmitBtn2, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_SubmitBtn2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_SubmitBtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_SubmitBtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_SubmitBtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_SubmitBtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sub_btn2;
//     label_sub_btn2 = lv_label_create(ui_SubmitBtn2);
//     lv_label_set_text(label_sub_btn2,"Save");
//     lv_obj_set_style_text_font(label_sub_btn2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sub_btn2);

//     ui_CancleBtn2 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_CancleBtn2, 55);
//     lv_obj_set_height(ui_CancleBtn2, 30);
//     lv_obj_set_x(ui_CancleBtn2, -128);
//     lv_obj_set_y(ui_CancleBtn2, 35);
//     lv_obj_set_align(ui_CancleBtn2, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_CancleBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_CancleBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_CancleBtn2, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CancleBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CancleBtn2, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CancleBtn2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CancleBtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CancleBtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_CancleBtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_CancleBtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_can_btn2;
//     label_can_btn2 = lv_label_create(ui_CancleBtn2);
//     lv_label_set_text(label_can_btn2,"Cancel");
//     lv_obj_set_style_text_font(label_can_btn2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_can_btn2);

//     ui_CardChangename3 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_CardChangename3, 143);
//     lv_obj_set_height(ui_CardChangename3, 90);
//     lv_obj_set_x(ui_CardChangename3, -163);
//     lv_obj_set_y(ui_CardChangename3, 110);
//     lv_obj_set_align(ui_CardChangename3, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_CardChangename3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_radius(ui_CardChangename3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_CardChangename3, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CardChangename3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CardChangename3, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CardChangename3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CardChangename3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CardChangename3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_ChangeName3 = lv_textarea_create(ui_Screen3);
//     lv_obj_set_width(ui_ChangeName3, 127);
//     lv_obj_set_height(ui_ChangeName3, 36);
//     lv_obj_set_x(ui_ChangeName3, -163);
//     lv_obj_set_y(ui_ChangeName3, 90);
//     lv_obj_set_align(ui_ChangeName3, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_ChangeName3, "ESP-32 Node3");
//     lv_obj_set_style_text_font(ui_ChangeName3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_SubmitBtn3 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_SubmitBtn3, 55);
//     lv_obj_set_height(ui_SubmitBtn3, 30);
//     lv_obj_set_x(ui_SubmitBtn3, -198);
//     lv_obj_set_y(ui_SubmitBtn3, 130);
//     lv_obj_set_align(ui_SubmitBtn3, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_SubmitBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_SubmitBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_SubmitBtn3, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_SubmitBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_SubmitBtn3, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_SubmitBtn3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_SubmitBtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_SubmitBtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_SubmitBtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_SubmitBtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sub_btn3;
//     label_sub_btn3 = lv_label_create(ui_SubmitBtn3);
//     lv_label_set_text(label_sub_btn3,"Save");
//     lv_obj_set_style_text_font(label_sub_btn3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sub_btn3);

//     ui_CancleBtn3 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_CancleBtn3, 55);
//     lv_obj_set_height(ui_CancleBtn3, 30);
//     lv_obj_set_x(ui_CancleBtn3, -128);
//     lv_obj_set_y(ui_CancleBtn3, 130);
//     lv_obj_set_align(ui_CancleBtn3, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_CancleBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_CancleBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_CancleBtn3, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CancleBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CancleBtn3, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CancleBtn3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CancleBtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CancleBtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_CancleBtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_CancleBtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_can_btn3;
//     label_can_btn3 = lv_label_create(ui_CancleBtn3);
//     lv_label_set_text(label_can_btn3,"Cancel");
//     lv_obj_set_style_text_font(label_can_btn3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_can_btn3);

//     ui_CardChangename4 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_CardChangename4, 143);
//     lv_obj_set_height(ui_CardChangename4, 90);
//     lv_obj_set_x(ui_CardChangename4, -15);
//     lv_obj_set_y(ui_CardChangename4, -77);
//     lv_obj_set_align(ui_CardChangename4, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_CardChangename4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_radius(ui_CardChangename4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_CardChangename4, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CardChangename4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CardChangename4, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CardChangename4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CardChangename4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CardChangename4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_ChangeName4 = lv_textarea_create(ui_Screen3);
//     lv_obj_set_width(ui_ChangeName4, 127);
//     lv_obj_set_height(ui_ChangeName4, 36);
//     lv_obj_set_x(ui_ChangeName4, -15);
//     lv_obj_set_y(ui_ChangeName4, -96);
//     lv_obj_set_align(ui_ChangeName4, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_ChangeName4, "ESP-32 Node4");
//     lv_obj_set_style_text_font(ui_ChangeName4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_SubmitBtn4 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_SubmitBtn4, 55);
//     lv_obj_set_height(ui_SubmitBtn4, 30);
//     lv_obj_set_x(ui_SubmitBtn4, -50);
//     lv_obj_set_y(ui_SubmitBtn4, -58);
//     lv_obj_set_align(ui_SubmitBtn4, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_SubmitBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_SubmitBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_SubmitBtn4, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_SubmitBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_SubmitBtn4, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_SubmitBtn4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_SubmitBtn4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_SubmitBtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_SubmitBtn4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_SubmitBtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sub_btn4;
//     label_sub_btn4 = lv_label_create(ui_SubmitBtn4);
//     lv_label_set_text(label_sub_btn4,"Save");
//     lv_obj_set_style_text_font(label_sub_btn4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sub_btn4);

//     ui_CancleBtn4 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_CancleBtn4, 55);
//     lv_obj_set_height(ui_CancleBtn4, 30);
//     lv_obj_set_x(ui_CancleBtn4, 20);
//     lv_obj_set_y(ui_CancleBtn4, -58);
//     lv_obj_set_align(ui_CancleBtn4, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_CancleBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_CancleBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_CancleBtn4, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CancleBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CancleBtn4, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CancleBtn4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CancleBtn4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CancleBtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_CancleBtn4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_CancleBtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_can_btn4;
//     label_can_btn4 = lv_label_create(ui_CancleBtn4);
//     lv_label_set_text(label_can_btn4,"Cancel");
//     lv_obj_set_style_text_font(label_can_btn4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_can_btn4);

//     ui_CardChangename5 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_CardChangename5, 143);
//     lv_obj_set_height(ui_CardChangename5, 90);
//     lv_obj_set_x(ui_CardChangename5, -15);
//     lv_obj_set_y(ui_CardChangename5, 16);
//     lv_obj_set_align(ui_CardChangename5, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_CardChangename5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_radius(ui_CardChangename5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_CardChangename5, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CardChangename5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CardChangename5, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CardChangename5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CardChangename5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CardChangename5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_ChangeName5 = lv_textarea_create(ui_Screen3);
//     lv_obj_set_width(ui_ChangeName5, 127);
//     lv_obj_set_height(ui_ChangeName5, 36);
//     lv_obj_set_x(ui_ChangeName5, -15);
//     lv_obj_set_y(ui_ChangeName5, -3);
//     lv_obj_set_align(ui_ChangeName5, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_ChangeName5, "ESP-32 Node5");
//     lv_obj_set_style_text_font(ui_ChangeName5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_SubmitBtn5 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_SubmitBtn5, 55);
//     lv_obj_set_height(ui_SubmitBtn5, 30);
//     lv_obj_set_x(ui_SubmitBtn5, -50);
//     lv_obj_set_y(ui_SubmitBtn5, 35);
//     lv_obj_set_align(ui_SubmitBtn5, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_SubmitBtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_SubmitBtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_SubmitBtn5, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_SubmitBtn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_SubmitBtn5, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_SubmitBtn5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_SubmitBtn5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_SubmitBtn5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_SubmitBtn5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_SubmitBtn5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sub_btn5;
//     label_sub_btn5 = lv_label_create(ui_SubmitBtn5);
//     lv_label_set_text(label_sub_btn5,"Save");
//     lv_obj_set_style_text_font(label_sub_btn5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sub_btn5);

//     ui_CancleBtn5 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_CancleBtn5, 55);
//     lv_obj_set_height(ui_CancleBtn5, 30);
//     lv_obj_set_x(ui_CancleBtn5, 20);
//     lv_obj_set_y(ui_CancleBtn5, 35);
//     lv_obj_set_align(ui_CancleBtn5, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_CancleBtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_CancleBtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_CancleBtn5, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CancleBtn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CancleBtn5, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CancleBtn5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CancleBtn5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CancleBtn5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_CancleBtn5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_CancleBtn5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_can_btn5;
//     label_can_btn5 = lv_label_create(ui_CancleBtn5);
//     lv_label_set_text(label_can_btn5,"Cancel");
//     lv_obj_set_style_text_font(label_can_btn5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_can_btn5);

//     ui_CardChangename6 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_CardChangename6, 143);
//     lv_obj_set_height(ui_CardChangename6, 90);
//     lv_obj_set_x(ui_CardChangename6, -15);
//     lv_obj_set_y(ui_CardChangename6, 110);
//     lv_obj_set_align(ui_CardChangename6, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_CardChangename6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_radius(ui_CardChangename6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_CardChangename6, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CardChangename6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CardChangename6, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CardChangename6, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CardChangename6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CardChangename6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_ChangeName6 = lv_textarea_create(ui_Screen3);
//     lv_obj_set_width(ui_ChangeName6, 127);
//     lv_obj_set_height(ui_ChangeName6, 36);
//     lv_obj_set_x(ui_ChangeName6, -15);
//     lv_obj_set_y(ui_ChangeName6, 90);
//     lv_obj_set_align(ui_ChangeName6, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_ChangeName6, "ESP-32 Node6");
//     lv_obj_set_style_text_font(ui_ChangeName6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_SubmitBtn6 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_SubmitBtn6, 55);
//     lv_obj_set_height(ui_SubmitBtn6, 30);
//     lv_obj_set_x(ui_SubmitBtn6, -50);
//     lv_obj_set_y(ui_SubmitBtn6, 130);
//     lv_obj_set_align(ui_SubmitBtn6, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_SubmitBtn6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_SubmitBtn6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_SubmitBtn6, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_SubmitBtn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_SubmitBtn6, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_SubmitBtn6, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_SubmitBtn6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_SubmitBtn6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_SubmitBtn6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_SubmitBtn6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sub_btn6;
//     label_sub_btn6 = lv_label_create(ui_SubmitBtn6);
//     lv_label_set_text(label_sub_btn6,"Save");
//     lv_obj_set_style_text_font(label_sub_btn6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sub_btn6);

//     ui_CancleBtn6 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_CancleBtn6, 55);
//     lv_obj_set_height(ui_CancleBtn6, 30);
//     lv_obj_set_x(ui_CancleBtn6, 20);
//     lv_obj_set_y(ui_CancleBtn6, 130);
//     lv_obj_set_align(ui_CancleBtn6, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_CancleBtn6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_CancleBtn6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_CancleBtn6, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CancleBtn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CancleBtn6, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CancleBtn6, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CancleBtn6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CancleBtn6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_CancleBtn6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_CancleBtn6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_can_btn6;
//     label_can_btn6 = lv_label_create(ui_CancleBtn6);
//     lv_label_set_text(label_can_btn6,"Cancel");
//     lv_obj_set_style_text_font(label_can_btn6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_can_btn6);

//     ui_CardChangename7 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_CardChangename7, 143);
//     lv_obj_set_height(ui_CardChangename7, 90);
//     lv_obj_set_x(ui_CardChangename7, 134);
//     lv_obj_set_y(ui_CardChangename7, -77);
//     lv_obj_set_align(ui_CardChangename7, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_CardChangename7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_radius(ui_CardChangename7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_CardChangename7, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CardChangename7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CardChangename7, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CardChangename7, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CardChangename7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CardChangename7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_CardChangename8 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_CardChangename8, 143);
//     lv_obj_set_height(ui_CardChangename8, 90);
//     lv_obj_set_x(ui_CardChangename8, 134);
//     lv_obj_set_y(ui_CardChangename8, 16);
//     lv_obj_set_align(ui_CardChangename8, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_CardChangename8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_radius(ui_CardChangename8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_CardChangename8, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CardChangename8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CardChangename8, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CardChangename8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CardChangename8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CardChangename8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_CardChangename9 = lv_obj_create(ui_Screen3);
//     lv_obj_set_width(ui_CardChangename9, 143);
//     lv_obj_set_height(ui_CardChangename9, 90);
//     lv_obj_set_x(ui_CardChangename9, 134);
//     lv_obj_set_y(ui_CardChangename9, 110);
//     lv_obj_set_align(ui_CardChangename9, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_CardChangename9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_radius(ui_CardChangename9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_color(ui_CardChangename9, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CardChangename9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CardChangename9, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CardChangename9, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CardChangename9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CardChangename9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_ChangeName7 = lv_textarea_create(ui_Screen3);
//     lv_obj_set_width(ui_ChangeName7, 127);
//     lv_obj_set_height(ui_ChangeName7, 36);
//     lv_obj_set_x(ui_ChangeName7, 134);
//     lv_obj_set_y(ui_ChangeName7, -96);
//     lv_obj_set_align(ui_ChangeName7, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_ChangeName7, "ESP-32 Node7");
//     lv_obj_set_style_text_font(ui_ChangeName7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    
//     ui_ChangeName8 = lv_textarea_create(ui_Screen3);
//     lv_obj_set_width(ui_ChangeName8, 127);
//     lv_obj_set_height(ui_ChangeName8, 36);
//     lv_obj_set_x(ui_ChangeName8, 134);
//     lv_obj_set_y(ui_ChangeName8, -3);
//     lv_obj_set_align(ui_ChangeName8, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_ChangeName8, "ESP-32 Node8");
//     lv_obj_set_style_text_font(ui_ChangeName8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_ChangeName9 = lv_textarea_create(ui_Screen3);
//     lv_obj_set_width(ui_ChangeName9, 127);
//     lv_obj_set_height(ui_ChangeName9, 36);
//     lv_obj_set_x(ui_ChangeName9, 134);
//     lv_obj_set_y(ui_ChangeName9, 90);
//     lv_obj_set_align(ui_ChangeName9, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_ChangeName9, "ESP-32 Node9");
//     lv_obj_set_style_text_font(ui_ChangeName9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_SubmitBtn7 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_SubmitBtn7, 55);
//     lv_obj_set_height(ui_SubmitBtn7, 30);
//     lv_obj_set_x(ui_SubmitBtn7, 99);
//     lv_obj_set_y(ui_SubmitBtn7, -58);
//     lv_obj_set_align(ui_SubmitBtn7, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_SubmitBtn7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_SubmitBtn7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_SubmitBtn7, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_SubmitBtn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_SubmitBtn7, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_SubmitBtn7, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_SubmitBtn7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_SubmitBtn7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_SubmitBtn7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_SubmitBtn7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sub_btn7;
//     label_sub_btn7 = lv_label_create(ui_SubmitBtn7);
//     lv_label_set_text(label_sub_btn7,"Save");
//     lv_obj_set_style_text_font(label_sub_btn7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sub_btn7);

//     ui_CancleBtn7 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_CancleBtn7, 55);
//     lv_obj_set_height(ui_CancleBtn7, 30);
//     lv_obj_set_x(ui_CancleBtn7, 168);
//     lv_obj_set_y(ui_CancleBtn7, -58);
//     lv_obj_set_align(ui_CancleBtn7, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_CancleBtn7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_CancleBtn7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_CancleBtn7, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CancleBtn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CancleBtn7, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CancleBtn7, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CancleBtn7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CancleBtn7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_CancleBtn7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_CancleBtn7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_can_btn7;
//     label_can_btn7 = lv_label_create(ui_CancleBtn7);
//     lv_label_set_text(label_can_btn7,"Cancel");
//     lv_obj_set_style_text_font(label_can_btn7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_can_btn7);

//     ui_SubmitBtn8 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_SubmitBtn8, 55);
//     lv_obj_set_height(ui_SubmitBtn8, 30);
//     lv_obj_set_x(ui_SubmitBtn8, 99);
//     lv_obj_set_y(ui_SubmitBtn8, 35);
//     lv_obj_set_align(ui_SubmitBtn8, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_SubmitBtn8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_SubmitBtn8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_SubmitBtn8, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_SubmitBtn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_SubmitBtn8, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_SubmitBtn8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_SubmitBtn8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_SubmitBtn8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_SubmitBtn8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_SubmitBtn8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sub_btn8;
//     label_sub_btn8 = lv_label_create(ui_SubmitBtn8);
//     lv_label_set_text(label_sub_btn8,"Save");
//     lv_obj_set_style_text_font(label_sub_btn8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sub_btn8);

//     ui_CancleBtn8 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_CancleBtn8, 55);
//     lv_obj_set_height(ui_CancleBtn8, 30);
//     lv_obj_set_x(ui_CancleBtn8, 168);
//     lv_obj_set_y(ui_CancleBtn8, 35);
//     lv_obj_set_align(ui_CancleBtn8, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_CancleBtn8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_CancleBtn8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_CancleBtn8, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CancleBtn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CancleBtn8, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CancleBtn8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CancleBtn8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CancleBtn8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_CancleBtn8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_CancleBtn8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_can_btn8;
//     label_can_btn8 = lv_label_create(ui_CancleBtn8);
//     lv_label_set_text(label_can_btn8,"Cancel");
//     lv_obj_set_style_text_font(label_can_btn8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_can_btn8);

//     ui_CancleBtn9 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_CancleBtn9, 55);
//     lv_obj_set_height(ui_CancleBtn9, 30);
//     lv_obj_set_x(ui_CancleBtn9, 168);
//     lv_obj_set_y(ui_CancleBtn9, 129);
//     lv_obj_set_align(ui_CancleBtn9, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_CancleBtn9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_CancleBtn9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_CancleBtn9, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_CancleBtn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_CancleBtn9, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_CancleBtn9, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_CancleBtn9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_CancleBtn9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_CancleBtn9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_CancleBtn9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_can_btn9;
//     label_can_btn9 = lv_label_create(ui_CancleBtn9);
//     lv_label_set_text(label_can_btn9,"Cancel");
//     lv_obj_set_style_text_font(label_can_btn9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_can_btn9);

//     ui_SubmitBtn9 = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_SubmitBtn9, 55);
//     lv_obj_set_height(ui_SubmitBtn9, 30);
//     lv_obj_set_x(ui_SubmitBtn9, 99);
//     lv_obj_set_y(ui_SubmitBtn9, 128);
//     lv_obj_set_align(ui_SubmitBtn9, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_SubmitBtn9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_SubmitBtn9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_SubmitBtn9, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_SubmitBtn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_SubmitBtn9, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_SubmitBtn9, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_SubmitBtn9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_SubmitBtn9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_SubmitBtn9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_SubmitBtn9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sub_btn9;
//     label_sub_btn9 = lv_label_create(ui_SubmitBtn9);
//     lv_label_set_text(label_sub_btn9,"Save");
//     lv_obj_set_style_text_font(label_sub_btn9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sub_btn9);


//     ui_changetoRe2btn = lv_btn_create(ui_Screen3);
//     lv_obj_set_width(ui_changetoRe2btn, 22);
//     lv_obj_set_height(ui_changetoRe2btn, 30);
//     lv_obj_set_x(ui_changetoRe2btn, 222);
//     lv_obj_set_y(ui_changetoRe2btn, 16);
//     lv_obj_set_align(ui_changetoRe2btn, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_changetoRe2btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_changetoRe2btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_changetoRe2btn, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_changetoRe2btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_color(ui_changetoRe2btn, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_grad_dir(ui_changetoRe2btn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_color(ui_changetoRe2btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_border_opa(ui_changetoRe2btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_color(ui_changetoRe2btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_shadow_opa(ui_changetoRe2btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_t * label_sym_btn3;
//     label_sym_btn3 = lv_label_create(ui_changetoRe2btn);
//     lv_label_set_text(label_sym_btn3,">");
//     lv_obj_set_style_text_font(label_sym_btn3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_center(label_sym_btn3);

//     lv_obj_add_event_cb(ui_changetoRe2btn, ui_event_changetoRe2btn, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_TabViewScr3,ui_event_TabviewScr3,LV_EVENT_ALL,NULL);

// }
