// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: TestDesign

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x57626C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaderPanel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_HeaderPanel2, 783);
    lv_obj_set_height(ui_HeaderPanel2, 37);
    lv_obj_set_x(ui_HeaderPanel2, 0);
    lv_obj_set_y(ui_HeaderPanel2, -143);
    lv_obj_set_align(ui_HeaderPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HeaderPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeaderPanel2, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaderPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HeaderPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HeaderPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateHeader1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_DateHeader1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateHeader1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateHeader1, 141);
    lv_obj_set_y(ui_DateHeader1, -141);
    lv_obj_set_align(ui_DateHeader1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateHeader1, "Wed, January 31 2023, 3:30 PM");
    lv_obj_set_style_text_color(ui_DateHeader1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateHeader1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateHeader1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Card7 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Card7, 143);
    lv_obj_set_height(ui_Card7, 135);
    lv_obj_set_x(ui_Card7, -129);
    lv_obj_set_y(ui_Card7, -54);
    lv_obj_set_align(ui_Card7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Card7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Card7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Card7, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Card7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Card7, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Card7, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Card7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Card7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemp7 = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_ArcTemp7, 90);
    lv_obj_set_height(ui_ArcTemp7, 90);
    lv_obj_set_x(ui_ArcTemp7, -125);
    lv_obj_set_y(ui_ArcTemp7, -52);
    lv_obj_set_align(ui_ArcTemp7, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcTemp7, -20, 10);
    lv_arc_set_value(ui_ArcTemp7, -10);
    lv_arc_set_bg_angles(ui_ArcTemp7, 100, 99);
    lv_obj_set_style_radius(ui_ArcTemp7, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcTemp7, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcTemp7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcTemp7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcTemp7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcTemp7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcTemp7, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp7, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ArcTemp7, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp7, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ArcTemp7, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcTemp7, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp7, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcBg7 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ArcBg7, 60);
    lv_obj_set_height(ui_ArcBg7, 60);
    lv_obj_set_x(ui_ArcBg7, -125);
    lv_obj_set_y(ui_ArcBg7, -51);
    lv_obj_set_align(ui_ArcBg7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcBg7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ArcBg7, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcBg7, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcBg7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ArcBg7, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ArcBg7, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArcBg7, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArcBg7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcBg7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1inner7 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Arc1inner7, 50);
    lv_obj_set_height(ui_Arc1inner7, 50);
    lv_obj_set_x(ui_Arc1inner7, -125);
    lv_obj_set_y(ui_Arc1inner7, -51);
    lv_obj_set_align(ui_Arc1inner7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1inner7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Arc1inner7, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Arc1inner7, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1inner7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Arc1inner7, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Arc1inner7, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Arc1inner7, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Arc1inner7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempCard7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_TempCard7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempCard7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempCard7, -125);
    lv_obj_set_y(ui_TempCard7, -50);
    lv_obj_set_align(ui_TempCard7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempCard7, "8° C");
    lv_obj_set_style_text_color(ui_TempCard7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempCard7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempCard7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeviceName7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_DeviceName7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceName7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceName7, -125);
    lv_obj_set_y(ui_DeviceName7, -107);
    lv_obj_set_align(ui_DeviceName7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeviceName7, "ESP32-Node 1");
    lv_obj_set_style_text_color(ui_DeviceName7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeviceName7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_DeviceName7, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeviceName7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LastUp7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LastUp7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LastUp7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LastUp7, -125);
    lv_obj_set_y(ui_LastUp7, 2);
    lv_obj_set_align(ui_LastUp7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LastUp7, "Last update : 3:50PM");
    lv_obj_set_style_text_color(ui_LastUp7, lv_color_hex(0xB3B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LastUp7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LastUp7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Card8 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Card8, 143);
    lv_obj_set_height(ui_Card8, 135);
    lv_obj_set_x(ui_Card8, 17);
    lv_obj_set_y(ui_Card8, -54);
    lv_obj_set_align(ui_Card8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Card8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Card8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Card8, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Card8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Card8, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Card8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Card8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Card8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeviceName8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_DeviceName8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceName8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceName8, 21);
    lv_obj_set_y(ui_DeviceName8, -107);
    lv_obj_set_align(ui_DeviceName8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeviceName8, "ESP32-Node 2");
    lv_obj_set_style_text_color(ui_DeviceName8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeviceName8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_DeviceName8, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeviceName8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemp8 = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_ArcTemp8, 90);
    lv_obj_set_height(ui_ArcTemp8, 90);
    lv_obj_set_x(ui_ArcTemp8, 20);
    lv_obj_set_y(ui_ArcTemp8, -51);
    lv_obj_set_align(ui_ArcTemp8, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcTemp8, -20, 10);
    lv_arc_set_value(ui_ArcTemp8, -10);
    lv_arc_set_bg_angles(ui_ArcTemp8, 100, 99);
    lv_obj_set_style_radius(ui_ArcTemp8, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcTemp8, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcTemp8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcTemp8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcTemp8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcTemp8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcTemp8, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp8, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ArcTemp8, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp8, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ArcTemp8, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcTemp8, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp8, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcBg8 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ArcBg8, 60);
    lv_obj_set_height(ui_ArcBg8, 60);
    lv_obj_set_x(ui_ArcBg8, 20);
    lv_obj_set_y(ui_ArcBg8, -51);
    lv_obj_set_align(ui_ArcBg8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcBg8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ArcBg8, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcBg8, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcBg8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ArcBg8, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ArcBg8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArcBg8, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArcBg8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcBg8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1inner8 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Arc1inner8, 50);
    lv_obj_set_height(ui_Arc1inner8, 50);
    lv_obj_set_x(ui_Arc1inner8, 20);
    lv_obj_set_y(ui_Arc1inner8, -51);
    lv_obj_set_align(ui_Arc1inner8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1inner8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Arc1inner8, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Arc1inner8, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1inner8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Arc1inner8, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Arc1inner8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Arc1inner8, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Arc1inner8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempCard8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_TempCard8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempCard8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempCard8, 20);
    lv_obj_set_y(ui_TempCard8, -51);
    lv_obj_set_align(ui_TempCard8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempCard8, "8° C");
    lv_obj_set_style_text_color(ui_TempCard8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempCard8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempCard8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LastUp8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LastUp8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LastUp8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LastUp8, 20);
    lv_obj_set_y(ui_LastUp8, 2);
    lv_obj_set_align(ui_LastUp8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LastUp8, "Last update : 3:50PM");
    lv_obj_set_style_text_color(ui_LastUp8, lv_color_hex(0xB3B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LastUp8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LastUp8, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Card9 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Card9, 143);
    lv_obj_set_height(ui_Card9, 135);
    lv_obj_set_x(ui_Card9, 163);
    lv_obj_set_y(ui_Card9, -54);
    lv_obj_set_align(ui_Card9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Card9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Card9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Card9, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Card9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Card9, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Card9, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Card9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Card9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeviceName9 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_DeviceName9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceName9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceName9, 167);
    lv_obj_set_y(ui_DeviceName9, -107);
    lv_obj_set_align(ui_DeviceName9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeviceName9, "ESP32-Node 3");
    lv_obj_set_style_text_color(ui_DeviceName9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeviceName9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_DeviceName9, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeviceName9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemp9 = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_ArcTemp9, 90);
    lv_obj_set_height(ui_ArcTemp9, 90);
    lv_obj_set_x(ui_ArcTemp9, 167);
    lv_obj_set_y(ui_ArcTemp9, -51);
    lv_obj_set_align(ui_ArcTemp9, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcTemp9, -20, 10);
    lv_arc_set_value(ui_ArcTemp9, -10);
    lv_arc_set_bg_angles(ui_ArcTemp9, 100, 99);
    lv_obj_set_style_radius(ui_ArcTemp9, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcTemp9, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcTemp9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcTemp9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcTemp9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcTemp9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcTemp9, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp9, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ArcTemp9, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp9, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ArcTemp9, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcTemp9, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp9, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcBg9 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ArcBg9, 60);
    lv_obj_set_height(ui_ArcBg9, 60);
    lv_obj_set_x(ui_ArcBg9, 167);
    lv_obj_set_y(ui_ArcBg9, -52);
    lv_obj_set_align(ui_ArcBg9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcBg9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ArcBg9, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcBg9, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcBg9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ArcBg9, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ArcBg9, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArcBg9, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArcBg9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcBg9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1inner9 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Arc1inner9, 50);
    lv_obj_set_height(ui_Arc1inner9, 50);
    lv_obj_set_x(ui_Arc1inner9, 167);
    lv_obj_set_y(ui_Arc1inner9, -52);
    lv_obj_set_align(ui_Arc1inner9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1inner9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Arc1inner9, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Arc1inner9, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1inner9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Arc1inner9, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Arc1inner9, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Arc1inner9, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Arc1inner9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempCard9 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_TempCard9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempCard9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempCard9, 167);
    lv_obj_set_y(ui_TempCard9, -51);
    lv_obj_set_align(ui_TempCard9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempCard9, "8° C");
    lv_obj_set_style_text_color(ui_TempCard9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempCard9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempCard9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LastUp9 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LastUp9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LastUp9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LastUp9, 167);
    lv_obj_set_y(ui_LastUp9, 2);
    lv_obj_set_align(ui_LastUp9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LastUp9, "Last update : 3:50PM");
    lv_obj_set_style_text_color(ui_LastUp9, lv_color_hex(0xB3B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LastUp9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LastUp9, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Card10 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Card10, 143);
    lv_obj_set_height(ui_Card10, 135);
    lv_obj_set_x(ui_Card10, -129);
    lv_obj_set_y(ui_Card10, 83);
    lv_obj_set_align(ui_Card10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Card10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Card10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Card10, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Card10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Card10, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Card10, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Card10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Card10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeviceName10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_DeviceName10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceName10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceName10, -125);
    lv_obj_set_y(ui_DeviceName10, 30);
    lv_obj_set_align(ui_DeviceName10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeviceName10, "ESP32-Node 4");
    lv_obj_set_style_text_color(ui_DeviceName10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeviceName10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_DeviceName10, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeviceName10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemp10 = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_ArcTemp10, 90);
    lv_obj_set_height(ui_ArcTemp10, 90);
    lv_obj_set_x(ui_ArcTemp10, -125);
    lv_obj_set_y(ui_ArcTemp10, 88);
    lv_obj_set_align(ui_ArcTemp10, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcTemp10, -20, 10);
    lv_arc_set_value(ui_ArcTemp10, -10);
    lv_arc_set_bg_angles(ui_ArcTemp10, 100, 99);
    lv_obj_set_style_radius(ui_ArcTemp10, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcTemp10, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcTemp10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcTemp10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcTemp10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcTemp10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcTemp10, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp10, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ArcTemp10, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp10, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ArcTemp10, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcTemp10, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp10, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcBg10 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ArcBg10, 60);
    lv_obj_set_height(ui_ArcBg10, 60);
    lv_obj_set_x(ui_ArcBg10, -125);
    lv_obj_set_y(ui_ArcBg10, 88);
    lv_obj_set_align(ui_ArcBg10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcBg10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ArcBg10, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcBg10, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcBg10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ArcBg10, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ArcBg10, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArcBg10, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArcBg10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcBg10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1inner10 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Arc1inner10, 50);
    lv_obj_set_height(ui_Arc1inner10, 50);
    lv_obj_set_x(ui_Arc1inner10, -125);
    lv_obj_set_y(ui_Arc1inner10, 88);
    lv_obj_set_align(ui_Arc1inner10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1inner10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Arc1inner10, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Arc1inner10, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1inner10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Arc1inner10, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Arc1inner10, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Arc1inner10, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Arc1inner10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempCard10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_TempCard10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempCard10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempCard10, -125);
    lv_obj_set_y(ui_TempCard10, 88);
    lv_obj_set_align(ui_TempCard10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempCard10, "8° C");
    lv_obj_set_style_text_color(ui_TempCard10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempCard10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempCard10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LastUp10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LastUp10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LastUp10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LastUp10, -125);
    lv_obj_set_y(ui_LastUp10, 141);
    lv_obj_set_align(ui_LastUp10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LastUp10, "Last update : 3:50PM");
    lv_obj_set_style_text_color(ui_LastUp10, lv_color_hex(0xB3B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LastUp10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LastUp10, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabViewScr2 = lv_tabview_create(ui_Screen2, LV_DIR_TOP, 60);
    lv_obj_set_width(ui_TabViewScr2, 255);
    lv_obj_set_height(ui_TabViewScr2, 37);
    lv_obj_set_x(ui_TabViewScr2, -113);
    lv_obj_set_y(ui_TabViewScr2, -143);
    lv_obj_set_align(ui_TabViewScr2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabViewScr2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabViewScr2, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabViewScr2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabViewScr2), lv_color_hex(0xB5B5B5),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabViewScr2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabViewScr2), &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabViewScr2), lv_color_hex(0x292929),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabViewScr2), 50,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_TabViewScr2), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_TabViewScr2), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(lv_tabview_get_tab_btns(ui_TabViewScr2), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(lv_tabview_get_tab_btns(ui_TabViewScr2), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(lv_tabview_get_tab_btns(ui_TabViewScr2), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(lv_tabview_get_tab_btns(ui_TabViewScr2), 25,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(lv_tabview_get_tab_btns(ui_TabViewScr2), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(lv_tabview_get_tab_btns(ui_TabViewScr2), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabViewScr2), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabViewScr2), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(lv_tabview_get_tab_btns(ui_TabViewScr2), LV_TEXT_ALIGN_CENTER,
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabViewScr2), &lv_font_montserrat_14,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabViewScr2), lv_color_hex(0x292929),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabViewScr2), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Monitoring1 = lv_tabview_add_tab(ui_TabViewScr2, "Monitor");

    ui_Rename1 = lv_tabview_add_tab(ui_TabViewScr2, "Rename");

    ui_Add_Device1 = lv_tabview_add_tab(ui_TabViewScr2, "Add device");

    ui_changetoScr1btn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_changetoScr1btn, 22);
    lv_obj_set_height(ui_changetoScr1btn, 30);
    lv_obj_set_x(ui_changetoScr1btn, -219);
    lv_obj_set_y(ui_changetoScr1btn, 16);
    lv_obj_set_align(ui_changetoScr1btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changetoScr1btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_changetoScr1btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_changetoScr1btn, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changetoScr1btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_changetoScr1btn, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_changetoScr1btn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changetoScr1btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changetoScr1btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changetoScr1btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changetoScr1btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t * label_sym_btn;
    label_sym_btn = lv_label_create(ui_changetoScr1btn);
    lv_label_set_text(label_sym_btn,"<");
    lv_obj_set_style_text_font(label_sym_btn, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(label_sym_btn);

    lv_obj_add_event_cb(ui_ArcTemp7, ui_event_ArcTemp7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcTemp8, ui_event_ArcTemp8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcTemp9, ui_event_ArcTemp9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcBg9, ui_event_ArcBg9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcTemp10, ui_event_ArcTemp10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changetoScr1btn, ui_event_changetoScr1btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabViewScr2,ui_event_TabviewScr2,LV_EVENT_ALL,NULL);
}
