// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: TestDesign

#ifndef _UI_COMP_CARD1_H
#define _UI_COMP_CARD1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Card1
#define UI_COMP_CARD1_CARD1 0
#define _UI_COMP_CARD1_NUM 1
lv_obj_t * ui_Card1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
