// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: TestDesign

#include "../ui.h"


// COMPONENT Card1

lv_obj_t * ui_Card1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Card1;
    cui_Card1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Card1, 221);
    lv_obj_set_height(cui_Card1, 123);
    lv_obj_set_x(cui_Card1, -116);
    lv_obj_set_y(cui_Card1, -53);
    lv_obj_set_align(cui_Card1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Card1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Card1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Card1, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Card1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Card1, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_Card1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Card1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Card1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CARD1_NUM);
    children[UI_COMP_CARD1_CARD1] = cui_Card1;
    lv_obj_add_event_cb(cui_Card1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Card1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Card1_create_hook(cui_Card1);
    return cui_Card1;
}

