// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: TestDesign

#ifndef _TESTDESIGN_UI_H
#define _TESTDESIGN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

LV_FONT_DECLARE(ui_font_PKNakhonSawan16);
LV_FONT_DECLARE(ui_font_TahoMaiBold16);
LV_FONT_DECLARE(ui_font_Arrow18);
LV_FONT_DECLARE(ui_font_Arrow24);
LV_FONT_DECLARE(ui_font_WiFi20);


/********************************************** CO-OBJECT **********************************************/

void create_ui_header(lv_obj_t *screen, int page);
void create_ui_card_infor(lv_obj_t * screen);
void hide_submit_setting_btn();
void unhide_submit_setting_btn();
void normal_state_pos();
void normal_pos_t_area_info_scr(int num);

void delete_obj_getstart();

void create_ui_view_btn(lv_obj_t * screen,lv_obj_t * view_btn_num);
void create_ui_chart(lv_obj_t * screen,lv_obj_t * view_chart_t_num,lv_obj_t * view_chart_num);
void create_ui_back_btn(lv_obj_t * screen,lv_obj_t * btn,int part);
// void create_ui_option_card(lv_obj_t * screen,lv_obj_t * option_card,lv_obj_t * name_op_t,lv_obj_t * pos_op_t);
void create_ui_op_name_t_area(lv_obj_t * screen,lv_obj_t * name_t_area);
void create_ui_op_pos_t_area(lv_obj_t * screen,lv_obj_t * pos_t_area);
void create_ui_save_btn(lv_obj_t * screen,lv_obj_t * save_btn);
void create_ui_cancel_btn(lv_obj_t * screen,lv_obj_t * cancel_btn);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
