// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: TestDesign

#ifndef _TESTDESIGN_UI_H
#define _TESTDESIGN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

/** Co-Event **/
extern lv_obj_t * ui_HeaderPanel;
extern lv_obj_t * ui_DateHeader;
extern lv_obj_t * BacktoMainBtn;
extern lv_obj_t * CardInfo;
void ui_event_BacktoMain1btn(lv_event_t * e);
void ui_event_BacktoMain2btn(lv_event_t * e);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Card1;
// void ui_event_ArcTemp1(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp1;
extern lv_obj_t * ui_ArcBg1;
extern lv_obj_t * ui_Arc1inner1;
extern lv_obj_t * ui_TempCard1;
extern lv_obj_t * ui_DeviceName1;
extern lv_obj_t * ui_LastUp1;
extern lv_obj_t * ui_Card2;
extern lv_obj_t * ui_DeviceName2;
// void ui_event_ArcTemp2(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp2;
extern lv_obj_t * ui_ArcBg2;
extern lv_obj_t * ui_Arc1inner2;
extern lv_obj_t * ui_TempCard2;
extern lv_obj_t * ui_LastUp2;
extern lv_obj_t * ui_Card3;
extern lv_obj_t * ui_DeviceName3;
// void ui_event_ArcTemp3(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp3;
void ui_event_ArcBg3(lv_event_t * e);
extern lv_obj_t * ui_ArcBg3;
extern lv_obj_t * ui_Arc1inner3;
extern lv_obj_t * ui_TempCard3;
extern lv_obj_t * ui_LastUp3;
extern lv_obj_t * ui_Card4;
extern lv_obj_t * ui_DeviceName4;
// void ui_event_ArcTemp4(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp4;
extern lv_obj_t * ui_ArcBg4;
extern lv_obj_t * ui_Arc1inner4;
extern lv_obj_t * ui_TempCard4;
extern lv_obj_t * ui_LastUp4;
extern lv_obj_t * ui_Card5;
extern lv_obj_t * ui_DeviceName5;
// void ui_event_ArcTemp5(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp5;
extern lv_obj_t * ui_ArcBg5;
extern lv_obj_t * ui_Arc1inner5;
extern lv_obj_t * ui_TempCard5;
extern lv_obj_t * ui_LastUp5;
extern lv_obj_t * ui_Card6;
extern lv_obj_t * ui_DeviceName6;
// void ui_event_ArcTemp6(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp6;
extern lv_obj_t * ui_ArcBg6;
extern lv_obj_t * ui_Arc1inner6;
extern lv_obj_t * ui_TempCard6;
extern lv_obj_t * ui_LastUp6;
// extern lv_obj_t * ui_TabViewScr1;
extern lv_obj_t * ui_Monitoring1;
extern lv_obj_t * ui_Rename1;
extern lv_obj_t * ui_Add_Device1;
void ui_event_changetoScr2btn(lv_event_t * e);
extern lv_obj_t * ui_changetoScr2btn;
// void ui_event_TabviewScr1(lv_event_t * e);
void ui_Card1_event(lv_event_t * e);
void ui_event_ArcTemp2(lv_event_t * e);
void ui_Card2_event(lv_event_t * e);
void ui_Card3_event(lv_event_t * e);
void ui_Card4_event(lv_event_t * e);
void ui_Card5_event(lv_event_t * e);
void ui_Card6_event(lv_event_t * e);
void ui_Card7_event(lv_event_t * e);
void ui_Card8_event(lv_event_t * e);
void ui_Card9_event(lv_event_t * e);
void ui_Card10_event(lv_event_t * e);

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Card7;
// void ui_event_ArcTemp7(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp7;
extern lv_obj_t * ui_ArcBg7;
extern lv_obj_t * ui_Arc1inner7;
extern lv_obj_t * ui_TempCard7;
extern lv_obj_t * ui_DeviceName7;
extern lv_obj_t * ui_LastUp7;
extern lv_obj_t * ui_Card8;
extern lv_obj_t * ui_DeviceName8;
// void ui_event_ArcTemp8(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp8;
extern lv_obj_t * ui_ArcBg8;
extern lv_obj_t * ui_Arc1inner8;
extern lv_obj_t * ui_TempCard8;
extern lv_obj_t * ui_LastUp8;
extern lv_obj_t * ui_Card9;
extern lv_obj_t * ui_DeviceName9;
// void ui_event_ArcTemp9(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp9;
void ui_event_ArcBg9(lv_event_t * e);
extern lv_obj_t * ui_ArcBg9;
extern lv_obj_t * ui_Arc1inner9;
extern lv_obj_t * ui_TempCard9;
extern lv_obj_t * ui_LastUp9;
extern lv_obj_t * ui_Card10;
extern lv_obj_t * ui_DeviceName10;
// void ui_event_ArcTemp10(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp10;
extern lv_obj_t * ui_ArcBg10;
extern lv_obj_t * ui_Arc1inner10;
extern lv_obj_t * ui_TempCard10;
extern lv_obj_t * ui_LastUp10;
// extern lv_obj_t * ui_TabViewScr2;
extern lv_obj_t * ui_Monitoring2;
extern lv_obj_t * ui_Rename2;
extern lv_obj_t * ui_Add_Device2;
void ui_event_changetoScr1btn(lv_event_t * e);
extern lv_obj_t * ui_changetoScr1btn;
extern lv_obj_t * ui____initial_actions0;
void ui_event_TabviewScr2(lv_event_t * e);

/** Device1 Information **/
void ui_InforScr1_screen_init(void);
extern lv_obj_t * ui_InfoScr1;
extern lv_obj_t * LastUpInfo1;
extern lv_obj_t * TextAreaInfo1;
extern lv_obj_t * SaveNamebtn1;
extern lv_obj_t * CancleNamebtn1;
extern lv_obj_t * ChartTempInfo1;
extern lv_obj_t * KeyboardInfo1;
void ui_event_KeyboardInfo1(lv_event_t * e);
void ui_event_SaveNamebtn1(lv_event_t * e);
void ui_event_TextAreaInfo1(lv_event_t * e);
void ui_event_CancleNamebtn1(lv_event_t * e);


/** Device2 Information **/
void ui_InforScr2_screen_init(void);
extern lv_obj_t * ui_InfoScr2;
extern lv_obj_t * LastUpInfo2;
extern lv_obj_t * TextAreaInfo2;
extern lv_obj_t * SaveNamebtn2;
extern lv_obj_t * CancleNamebtn2;
extern lv_obj_t * ChartTempInfo2;
extern lv_obj_t * KeyboardInfo2;
extern lv_chart_series_t * ChartTempInfo2_series_1;
void ui_event_SaveNamebtn2(lv_event_t * e);
void ui_event_KeyboardInfo2(lv_event_t * e);
void ui_event_TextAreaInfo2(lv_event_t * e);
void ui_event_CancleNamebtn2(lv_event_t * e);

/** Device3 Information **/
void ui_InforScr3_screen_init(void);
extern lv_obj_t * ui_InfoScr3;
extern lv_obj_t * LastUpInfo3;
extern lv_obj_t * TextAreaInfo3; 
extern lv_obj_t * SaveNamebtn3;
extern lv_obj_t * CancleNamebtn3;
extern lv_obj_t * ChartTempInfo3;
extern lv_obj_t * KeyboardInfo3;
extern lv_chart_series_t * ChartTempInfo3_series_1;
void ui_event_SaveNamebtn3(lv_event_t * e);
void ui_event_KeyboardInfo3(lv_event_t * e);
void ui_event_TextAreaInfo3(lv_event_t * e);
void ui_event_CancleNamebtn3(lv_event_t * e);

/** Device4 Information **/
void ui_InforScr4_screen_init(void);
extern lv_obj_t * ui_InfoScr4;
extern lv_obj_t * LastUpInfo4;
extern lv_obj_t * TextAreaInfo4;
extern lv_obj_t * SaveNamebtn4;
extern lv_obj_t * CancleNamebtn4;
extern lv_obj_t * ChartTempInfo4;
extern lv_obj_t * KeyboardInfo4;
extern lv_chart_series_t * ChartTempInfo4_series_1;
void ui_event_SaveNamebtn4(lv_event_t * e);
void ui_event_KeyboardInfo4(lv_event_t * e);
void ui_event_TextAreaInfo4(lv_event_t * e);
void ui_event_CancleNamebtn4(lv_event_t * e);

/** Device5 Information **/
void ui_InforScr5_screen_init(void);
extern lv_obj_t * ui_InfoScr5;
extern lv_obj_t * LastUpInfo5;
extern lv_obj_t * TextAreaInfo5;
extern lv_obj_t * SaveNamebtn5;
extern lv_obj_t * CancleNamebtn5;
extern lv_obj_t * ChartTempInfo5;
extern lv_obj_t * KeyboardInfo5;
extern lv_chart_series_t * ChartTempInfo5_series_1;
void ui_event_SaveNamebtn5(lv_event_t * e);
void ui_event_KeyboardInfo5(lv_event_t * e);
void ui_event_TextAreaInfo5(lv_event_t * e);
void ui_event_CancleNamebtn5(lv_event_t * e);

/** Device6 Information **/
void ui_InforScr6_screen_init(void);
extern lv_obj_t * ui_InfoScr6;
extern lv_obj_t * LastUpInfo6;
extern lv_obj_t * TextAreaInfo6;
extern lv_obj_t * SaveNamebtn6;
extern lv_obj_t * CancleNamebtn6;
extern lv_obj_t * ChartTempInfo6;
extern lv_obj_t * KeyboardInfo6;
extern lv_chart_series_t * ChartTempInfo6_series_1;
void ui_event_SaveNamebtn6(lv_event_t * e);
void ui_event_KeyboardInfo6(lv_event_t * e);
void ui_event_TextAreaInfo6(lv_event_t * e);
void ui_event_CancleNamebtn6(lv_event_t * e);

/** Device7 Information **/
void ui_InforScr7_screen_init(void);
extern lv_obj_t * ui_InfoScr7;
extern lv_obj_t * LastUpInfo7;
extern lv_obj_t * TextAreaInfo7;
extern lv_obj_t * SaveNamebtn7;
extern lv_obj_t * CancleNamebtn7;
extern lv_obj_t * ChartTempInfo7;
extern lv_obj_t * KeyboardInfo7;
extern lv_chart_series_t * ChartTempInfo7_series_1;
void ui_event_SaveNamebtn7(lv_event_t * e);
void ui_event_KeyboardInfo7(lv_event_t * e);
void ui_event_TextAreaInfo7(lv_event_t * e);
void ui_event_CancleNamebtn7(lv_event_t * e);

/** Device8 Information **/
void ui_InforScr8_screen_init(void);
extern lv_obj_t * ui_InfoScr8;
extern lv_obj_t * LastUpInfo8;
extern lv_obj_t * TextAreaInfo8;
extern lv_obj_t * SaveNamebtn8;
extern lv_obj_t * CancleNamebtn8;
extern lv_obj_t * ChartTempInfo8;
extern lv_obj_t * KeyboardInfo8;
extern lv_chart_series_t * ChartTempInfo8_series_1;
void ui_event_SaveNamebtn8(lv_event_t * e);
void ui_event_KeyboardInfo8(lv_event_t * e);
void ui_event_TextAreaInfo8(lv_event_t * e);
void ui_event_CancleNamebtn8(lv_event_t * e);

/** Device9 Information **/
void ui_InforScr9_screen_init(void);
extern lv_obj_t * ui_InfoScr9;
extern lv_obj_t * LastUpInfo9;
extern lv_obj_t * TextAreaInfo9;
extern lv_obj_t * SaveNamebtn9;
extern lv_obj_t * CancleNamebtn9;
extern lv_obj_t * ChartTempInfo9;
extern lv_obj_t * KeyboardInfo9;
extern lv_chart_series_t * ChartTempInfo9_series_1;
void ui_event_SaveNamebtn9(lv_event_t * e);
void ui_event_KeyboardInfo9(lv_event_t * e);
void ui_event_TextAreaInfo9(lv_event_t * e);
void ui_event_CancleNamebtn9(lv_event_t * e);

/** Device10 Information **/
void ui_InforScr10_screen_init(void);
extern lv_obj_t * ui_InfoScr10;
extern lv_obj_t * LastUpInfo10;
extern lv_obj_t * TextAreaInfo10;
extern lv_obj_t * SaveNamebtn10;
extern lv_obj_t * CancleNamebtn10;
extern lv_obj_t * ChartTempInfo10;
extern lv_obj_t * KeyboardInfo10;
extern lv_chart_series_t * ChartTempInfo10_series_1;
void ui_event_SaveNamebtn10(lv_event_t * e);
void ui_event_KeyboardInfo10(lv_event_t * e);
void ui_event_TextAreaInfo10(lv_event_t * e);
void ui_event_CancleNamebtn10(lv_event_t * e);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
